### ISSUE TITLE
Error: Object variable or With block variable not set

### ISSUE THREAD

**Issue by Rashmik4444** [Sven-Bo/Integrate-GPT4-in-Excel-using-VBA#1]
Thank you So much for your detail videos, they are very helpful in our work. 
While Adding ChatGPT 4 in Excel, I am running you code and it is creating new Output Sheet but Showing error in Output i.e. 
**Error: Object variable or With block variable not set**
I have imported Jason Converter and ChatGpt Code also Updated API Key in Code 
Not able to resolve this issue . Kindly Help. 
Thanking you in Advance.

**Comment by Sven-Bo** [comment]
Sorry, with that bit of information, I cannot help you. You might want to note down the error number that is causing the issue. I am closing the issue for now.
